openapi: 3.0.3
info:
  title: 'Craig learning Lumen'
  description: 'A Laravel Developers Guide to Lumen'
  version: 1.0.0
servers:
  -
    url: 'http://lumen.test'
paths:
  /cities:
    get:
      summary: 'City: Display a listing of the City resource.'
      description: 'City List'
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            text/plain:
              schema:
                type: string
                example: "\n[\n    {\n        id: 1,\n        name: \"Cary\",\n        created_at: \"2021-10-30T00:42:41.000000Z\",\n        updated_at: \"2021-10-30T00:42:41.000000Z\"\n    },\n    {\n        id: 2,\n        name: \"Durham\",\n        created_at: \"2021-10-30T00:42:41.000000Z\",\n        updated_at: \"2021-10-30T00:42:41.000000Z\"\n    }\n]\n"
      tags:
        - Cities
      security: []
    post:
      summary: 'City: Store a newly created City resource in storage.'
      description: 'City Store'
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            text/plain:
              schema:
                type: string
                example: "\n{\n    id: 1,\n    name: \"Makenzie Mayert\",\n    created_at: \"2021-10-30T00:42:41.000000Z\",\n    updated_at: \"2021-10-30T00:42:41.000000Z\"\n}\n"
      tags:
        - Cities
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 'Name of city. Example Durham'
                  example: et
              required:
                - name
      security: []
  '/cities/{city}':
    get:
      summary: 'City: Display the specified City resource.'
      description: 'City Show'
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            text/plain:
              schema:
                type: string
                example: "\n{\n    id: 1,\n    name: \"Makenzie Mayert\",\n    created_at: \"2021-10-30T00:42:41.000000Z\",\n    updated_at: \"2021-10-30T00:42:41.000000Z\"\n}\n"
      tags:
        - Cities
      security: []
    delete:
      summary: 'City: Remove the specified City resource from storage.'
      description: 'City Destroy'
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        500:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'Server Error'
                properties:
                  message:
                    type: string
                    example: 'Server Error'
      tags:
        - Cities
      security: []
    put:
      summary: 'City: Update the specified resource in storage.'
      description: 'City Update'
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            text/plain:
              schema:
                type: string
                example: "\n{\n    id: 1,\n    name: \"Makenzie Mayert\",\n    created_at: \"2021-10-30T00:42:41.000000Z\",\n    updated_at: \"2021-10-30T00:42:41.000000Z\"\n}\n"
      tags:
        - Cities
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 'Name of city. Example Durham'
                  example: laborum
              required:
                - name
      security: []
    parameters:
      -
        in: path
        name: city
        description: ''
        example: eveniet
        required: true
        schema:
          type: string
  /:
    get:
      summary: ''
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            text/plain:
              schema:
                type: string
                example: 'Lumen (8.3.1) (Laravel Components ^8.0)'
      tags:
        - Endpoints
      security: []
tags:
  -
    name: Cities
    description: ''
  -
    name: Endpoints
    description: ''
